### ISSUE TITLE
NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by MeblIkea** [tomas-teijeiro/wavtobeep#3]
Hi, when I launch your program, he print :

C:\Users\MeblIkea\Desktop>python wavtobeep.py C:\Users\MeblIkea\Music\mymusic.wav
Traceback (most recent call last):
  File "C:\Users\MeblIkea\Desktop\wavtobeep.py", line 23, in <module>
    for o in xrange(10)
NameError: name 'xrange' is not defined

Bye.

**Comment by terra1149** [comment]
I had the same issue. xrange was replaced by range in python3, so xrange only works in python2 and below. However I never got it to run with python2 either, that's your issue though.
